# SPDX-License-Identifier: MIT
"""Cross-platform build and tooling skills — CMake, vcpkg, package managers."""

from specsmith.skills import SkillDomain, SkillEntry

SKILLS: list[SkillEntry] = [
    SkillEntry(
        slug="cmake-cross-platform",
        name="CMake — cross-platform builds, vcpkg, conan, presets",
        description=(
            "CMake cross-platform build system: modern target-based configuration, "
            "vcpkg/conan dependency management, CMake presets, and CI integration."
        ),
        domain=SkillDomain.CROSS_PLATFORM,
        tags=[
            "cmake",
            "vcpkg",
            "conan",
            "cross-platform",
            "c",
            "cpp",
            "build",
            "ninja",
            "presets",
            "windows",
            "linux",
            "macos",
        ],
        platforms=["windows", "linux", "macos"],
        prerequisites=["cmake", "ninja"],
        body="""\
# CMake Cross-Platform Skill

## Modern CMakeLists.txt (target-based)
```cmake
cmake_minimum_required(VERSION 3.25)
project(myapp VERSION 1.0.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)   # for clangd / clang-tidy

add_executable(myapp
    src/main.cpp
    src/engine.cpp)

target_include_directories(myapp
    PRIVATE src/include
    PUBLIC  include)

target_compile_options(myapp PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4 /WX>
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall -Wextra -Werror>)

target_link_libraries(myapp
    PRIVATE fmt::fmt spdlog::spdlog)
```

## CMake Presets (CMakePresets.json)
```json
{
  "version": 6,
  "configurePresets": [
    {
      "name": "linux-release",
      "generator": "Ninja",
      "binaryDir": "build/linux-release",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      }
    },
    {
      "name": "windows-msvc",
      "generator": "Visual Studio 17 2022",
      "binaryDir": "build/windows-msvc",
      "architecture": {"value": "x64", "strategy": "set"},
      "cacheVariables": {
        "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      }
    }
  ],
  "buildPresets": [
    {"name": "linux-release", "configurePreset": "linux-release"},
    {"name": "windows-release", "configurePreset": "windows-msvc", "configuration": "Release"}
  ]
}
```
```bash
cmake --preset linux-release
cmake --build --preset linux-release
cmake --list-presets               # list all presets
```

## vcpkg dependency management
```bash
# Bootstrap vcpkg
git clone https://github.com/microsoft/vcpkg $HOME/vcpkg
$HOME/vcpkg/bootstrap-vcpkg.sh      # Linux/macOS
%USERPROFILE%\\vcpkg\\bootstrap-vcpkg.bat  # Windows

# Install packages (manifest mode — recommended)
# vcpkg.json in project root:
{
  "name": "myapp",
  "version": "1.0.0",
  "dependencies": [
    "fmt", "spdlog",
    {"name": "boost-filesystem", "version>=": "1.83.0"}
  ]
}
# Set VCPKG_ROOT and use CMAKE_TOOLCHAIN_FILE=.../vcpkg.cmake
cmake --preset linux-release   # auto-installs from vcpkg.json

vcpkg search boost              # search packages
vcpkg list                      # show installed
vcpkg install fmt:x64-windows   # manual install (classic mode)
```

## Conan 2 dependency management
```bash
pip install conan
conan profile detect            # auto-detect host profile
# conanfile.txt:
[requires]
fmt/10.2.1
spdlog/1.13.0
[generators]
CMakeDeps
CMakeToolchain

conan install . --build=missing  # install + generate CMake files
cmake -B build -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake
cmake --build build
```

## Cross-compilation with CMake toolchain
```cmake
# toolchain-aarch64-linux.cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_FIND_ROOT_PATH /opt/sysroot-aarch64)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
```bash
cmake -B build-arm -DCMAKE_TOOLCHAIN_FILE=toolchain-aarch64-linux.cmake
cmake --build build-arm
```

## Common pitfalls
- CMake 3.25+: use `cmake --preset`; older: pass `-G Ninja -B build`.
- MSVC: open "Developer Command Prompt" or use `vcvarsall.bat x64`.
- vcpkg: set `VCPKG_ROOT` env var system-wide; don't hardcode paths.
- `compile_commands.json`: generated by Ninja/Make, not MSVC
  (use `CMAKE_EXPORT_COMPILE_COMMANDS=ON`).
""",
    ),
    SkillEntry(
        slug="package-managers",
        name="Package Managers — brew, winget, scoop, apt, nix (cross-platform)",
        description=(
            "Cross-platform package manager workflows: Homebrew (macOS/Linux), "
            "winget/scoop/choco (Windows), apt/dnf (Linux), and Nix for reproducibility."
        ),
        domain=SkillDomain.CROSS_PLATFORM,
        tags=[
            "homebrew",
            "brew",
            "winget",
            "scoop",
            "chocolatey",
            "apt",
            "dnf",
            "nix",
            "package-manager",
            "cross-platform",
        ],
        platforms=["windows", "linux", "macos"],
        prerequisites=[],
        body="""\
# Cross-Platform Package Managers Skill

## macOS — Homebrew
```bash
# Install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install git cmake ninja python@3.12 node
brew install --cask visual-studio-code docker
brew upgrade                    # upgrade all packages
brew outdated                   # list outdatable packages
brew cleanup                    # remove old versions
brew leaves                     # show top-level installed packages
brew bundle dump                # export Brewfile
brew bundle install             # install from Brewfile

# Brewfile (commit to repo for team consistency)
tap "homebrew/cask"
brew "git"
brew "cmake"
brew "ninja"
cask "docker"
cask "visual-studio-code"
```

## Linux — apt (Debian/Ubuntu)
```bash
sudo apt update && sudo apt upgrade -y
sudo apt install -y git cmake ninja-build python3 python3-pip nodejs npm
sudo apt install -y build-essential gcc g++ clang clang-tidy clang-format

# Add third-party repo (example: GitHub CLI)
type -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
    sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] \
    https://cli.github.com/packages stable main" \
    | sudo tee /etc/apt/sources.list.d/github-cli.list
sudo apt update && sudo apt install gh

# List installed packages
dpkg -l | grep <pattern>
apt list --installed
```

## Linux — dnf (RHEL/Fedora/AlmaLinux)
```bash
sudo dnf update -y
sudo dnf install -y git cmake ninja-build python3 nodejs npm gcc gcc-c++ clang
sudo dnf groupinstall "Development Tools"
dnf list installed | grep <pattern>
```

## Windows — winget (built-in Windows Package Manager)
```powershell
winget search git
winget install Git.Git
winget install Kitware.CMake
winget install Python.Python.3.12
winget install Microsoft.VisualStudioCode
winget install Docker.DockerDesktop
winget upgrade --all                      # upgrade everything
winget export -o packages.json            # export installed list
winget import -i packages.json            # import and install
```

## Windows — Scoop (developer-friendly, no admin needed)
```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

scoop install git cmake ninja python nodejs
scoop bucket add extras
scoop install vscode
scoop update *           # update all
scoop status             # show updatable
scoop export > scoop-packages.json   # export
```

## Nix — reproducible, cross-platform
```bash
# Install Nix (Linux/macOS)
sh <(curl -L https://nixos.org/nix/install) --daemon

# nix shell — ephemeral env (no install)
nix shell nixpkgs#git nixpkgs#cmake nixpkgs#ninja

# flake.nix (project-level devShell)
{
  outputs = { nixpkgs, ... }: {
    devShell.x86_64-linux = nixpkgs.legacyPackages.x86_64-linux.mkShell {
      packages = with nixpkgs.legacyPackages.x86_64-linux; [
        git cmake ninja python3 nodejs
      ];
    };
  };
}
# Enter dev shell: nix develop
```

## Common pitfalls
- Homebrew on Apple Silicon: installs to `/opt/homebrew/`; Intel: `/usr/local/`.
- winget: requires Windows Package Manager app from Store on older Windows 10.
- Scoop: installs to `~/scoop/` — no admin rights needed, great for CI.
- Nix: steep learning curve but ultimate reproducibility; use nix-shell for experiments.
""",
    ),
]
