"""Per-run metrics collection for the governance efficiency benchmark.

A RunResult captures everything recorded during a single task × condition run.
BenchReport aggregates multiple RunResults into comparison tables.

Primary metric: cost_of_pass = total_cost_usd / pass_rate
  where pass_rate = fraction of runs for this (task, condition) that pass.

Secondary metrics (all per run):
  input_tokens     – tokens in the full context window (system + history)
  output_tokens    – tokens generated by the model
  total_tokens     – input + output
  api_cost_usd     – estimated API cost at list prices
  rework_turns     – number of turns required (>1 = rework happened)
  wall_clock_s     – elapsed wall-clock seconds
  lint_passed      – ruff check . returned exit 0
  tests_passed     – pytest returned exit 0
  quality_score    – LLM judge 0.0–1.0 (see judge.py)
  governance_turns – turns consumed by governance overhead (preflight, verify, etc.)
"""

from __future__ import annotations

import statistics
from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Pricing constants (USD per 1K tokens, list prices as of Q2 2026)
# Update when model pricing changes.
# ---------------------------------------------------------------------------

MODEL_PRICING: dict[str, tuple[float, float]] = {
    # (input_per_1k, output_per_1k)
    "claude-opus-4-5":      (0.015,  0.075),
    "claude-sonnet-4-5":    (0.003,  0.015),
    "claude-haiku-4-5":     (0.00025, 0.00125),
    "gpt-4o":               (0.005,  0.015),
    "gpt-4o-mini":          (0.00015, 0.0006),
    "gpt-4.1":              (0.002,  0.008),
    "gemini-3-flash":       (0.00035, 0.00105),
    # Fallback
    "unknown":              (0.003,  0.015),
}


def estimate_cost(model: str, input_tokens: int, output_tokens: int) -> float:
    """Return estimated API cost in USD for a single call."""
    inp_rate, out_rate = MODEL_PRICING.get(model, MODEL_PRICING["unknown"])
    return (input_tokens / 1000 * inp_rate) + (output_tokens / 1000 * out_rate)


# ---------------------------------------------------------------------------
# RunResult
# ---------------------------------------------------------------------------

@dataclass
class RunResult:
    """Metrics for a single task × condition × repetition run."""

    task_id: str
    condition_id: str
    rep: int  # 1-based repetition index

    # Token usage
    input_tokens: int = 0
    output_tokens: int = 0
    model: str = "unknown"

    # Derived cost (set by record() or computed lazily)
    api_cost_usd: float = 0.0

    # Quality
    lint_passed: bool = False
    tests_passed: bool = False
    quality_score: float = 0.0   # 0.0–1.0 from LLM judge
    judge_rationale: str = ""

    # Efficiency
    rework_turns: int = 1        # ≥1 (1 = first-pass success)
    governance_turns: int = 0    # turns consumed by governance overhead
    wall_clock_s: float = 0.0

    # Error tracking
    error: str | None = None
    skipped: bool = False

    # Raw outputs for post-hoc analysis
    agent_transcript: list[dict] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.api_cost_usd == 0.0 and self.input_tokens > 0:
            self.api_cost_usd = estimate_cost(
                self.model, self.input_tokens, self.output_tokens
            )

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens

    @property
    def passed(self) -> bool:
        """A run passes if lint and tests both pass."""
        return self.lint_passed and self.tests_passed

    @property
    def total_turns(self) -> int:
        return self.rework_turns + self.governance_turns


# ---------------------------------------------------------------------------
# Aggregate statistics for (task, condition) slice
# ---------------------------------------------------------------------------

@dataclass
class SliceStats:
    """Aggregate statistics over N repetitions of a (task, condition) slice."""

    task_id: str
    condition_id: str
    n_reps: int

    pass_rate: float = 0.0
    mean_input_tokens: float = 0.0
    mean_output_tokens: float = 0.0
    mean_total_tokens: float = 0.0
    mean_api_cost_usd: float = 0.0
    mean_quality_score: float = 0.0
    mean_rework_turns: float = 0.0
    mean_governance_turns: float = 0.0
    mean_wall_clock_s: float = 0.0

    # Std-devs (None when n_reps < 2)
    std_total_tokens: float | None = None
    std_api_cost_usd: float | None = None
    std_quality_score: float | None = None

    # The headline metric
    cost_of_pass: float = float("inf")  # total_cost / pass_rate; inf if pass_rate == 0

    @classmethod
    def from_runs(cls, runs: list[RunResult]) -> SliceStats:
        """Compute aggregate stats from a list of RunResults."""
        if not runs:
            raise ValueError("Cannot compute stats from empty run list")

        task_id = runs[0].task_id
        condition_id = runs[0].condition_id
        n = len(runs)

        valid = [r for r in runs if not r.skipped]
        if not valid:
            return cls(task_id=task_id, condition_id=condition_id, n_reps=n)

        pass_rate = sum(1 for r in valid if r.passed) / len(valid)
        mean_cost = statistics.mean(r.api_cost_usd for r in valid)

        cost_of_pass = (mean_cost / pass_rate) if pass_rate > 0 else float("inf")

        stats = cls(
            task_id=task_id,
            condition_id=condition_id,
            n_reps=n,
            pass_rate=pass_rate,
            mean_input_tokens=statistics.mean(r.input_tokens for r in valid),
            mean_output_tokens=statistics.mean(r.output_tokens for r in valid),
            mean_total_tokens=statistics.mean(r.total_tokens for r in valid),
            mean_api_cost_usd=mean_cost,
            mean_quality_score=statistics.mean(r.quality_score for r in valid),
            mean_rework_turns=statistics.mean(r.rework_turns for r in valid),
            mean_governance_turns=statistics.mean(r.governance_turns for r in valid),
            mean_wall_clock_s=statistics.mean(r.wall_clock_s for r in valid),
            cost_of_pass=cost_of_pass,
        )

        if len(valid) >= 2:
            stats.std_total_tokens = statistics.stdev(r.total_tokens for r in valid)
            stats.std_api_cost_usd = statistics.stdev(r.api_cost_usd for r in valid)
            stats.std_quality_score = statistics.stdev(r.quality_score for r in valid)

        return stats


# ---------------------------------------------------------------------------
# Full benchmark report container
# ---------------------------------------------------------------------------

@dataclass
class BenchReport:
    """Aggregated results across all tasks × conditions."""

    runs: list[RunResult] = field(default_factory=list)

    def slices(self) -> list[SliceStats]:
        """Return SliceStats for every (task, condition) combination."""
        from itertools import groupby

        def _run_key(r: RunResult) -> tuple[str, str]:
            return (r.task_id, r.condition_id)

        sorted_runs = sorted(self.runs, key=_run_key)
        return [
            SliceStats.from_runs(list(group))
            for _, group in groupby(sorted_runs, key=_run_key)
        ]

    def condition_summary(self) -> dict[str, dict]:
        """Roll up per-condition means across all tasks."""
        per_condition: dict[str, list[SliceStats]] = {}
        for s in self.slices():
            per_condition.setdefault(s.condition_id, []).append(s)

        summary = {}
        for cid, slices in per_condition.items():
            finite_cop = [s.cost_of_pass for s in slices if s.cost_of_pass < float("inf")]
            summary[cid] = {
                "mean_pass_rate": statistics.mean(s.pass_rate for s in slices),
                "mean_total_tokens": statistics.mean(s.mean_total_tokens for s in slices),
                "mean_api_cost_usd": statistics.mean(s.mean_api_cost_usd for s in slices),
                "mean_quality_score": statistics.mean(s.mean_quality_score for s in slices),
                "mean_cost_of_pass": statistics.mean(finite_cop) if finite_cop else float("inf"),
                "n_tasks": len(slices),
            }
        return summary
