# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Layer1Labs Silicon, Inc. All rights reserved.
"""Codity.ai integration adapter.

Generates a GitHub Actions (or GitLab CI / Azure Pipelines) workflow that
runs ``codity review --staged`` on every pull-request, plus appends a setup
checklist to LEDGER.md and writes a starter Codity configuration hint.
"""

from __future__ import annotations

from pathlib import Path

from specsmith.config import ProjectConfig
from specsmith.integrations.base import AgentAdapter


class CodityAdapter(AgentAdapter):
    """Scaffold Codity.ai AI-code-review integration files."""

    @property
    def name(self) -> str:
        return "codity"

    @property
    def description(self) -> str:
        return "Codity.ai AI code review (.github/workflows/codity-review.yml)"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, config: ProjectConfig, target: Path) -> list[Path]:
        """Generate Codity.ai integration files.

        Creates:
        - ``.github/workflows/codity-review.yml`` (or GitLab/Azure variant)
        - ``docs/codity-setup.md`` — one-time setup checklist
        Appends:
        - ``LEDGER.md`` — Codity setup TODO entry
        """
        created: list[Path] = []

        vcs = self._detect_vcs(target)
        workflow_path = self._write_workflow(config, target, vcs)
        if workflow_path:
            created.append(workflow_path)

        setup_doc = self._write_setup_doc(config, target, vcs)
        created.append(setup_doc)

        self._append_ledger(target, vcs)

        return created

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _detect_vcs(self, target: Path) -> str:
        """Detect VCS host from scaffold.yml or directory layout.

        Returns one of: ``"github"``, ``"gitlab"``, ``"azure"``.
        Defaults to ``"github"`` when the host cannot be determined.
        """
        scaffold = target / "scaffold.yml"
        if scaffold.exists():
            text = scaffold.read_text(encoding="utf-8")
            if "gitlab" in text.lower():
                return "gitlab"
            if "azure" in text.lower() or "azuredevops" in text.lower():
                return "azure"
        # Structural heuristics
        if (target / ".gitlab-ci.yml").exists():
            return "gitlab"
        if (target / "azure-pipelines.yml").exists():
            return "azure"
        return "github"

    # ---- workflow writers -------------------------------------------

    def _write_workflow(self, config: ProjectConfig, target: Path, vcs: str) -> Path | None:
        if vcs == "github":
            return self._write_github_workflow(config, target)
        if vcs == "gitlab":
            return self._write_gitlab_workflow(config, target)
        if vcs == "azure":
            return self._write_azure_workflow(config, target)
        return None

    def _write_github_workflow(self, config: ProjectConfig, target: Path) -> Path:
        workflows_dir = target / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)
        workflow_path = workflows_dir / "codity-review.yml"
        content = f"""\
# Codity.ai AI Code Review — {config.name}
# Generated by specsmith (specsmith integrate codity)
#
# Prerequisites:
#   1. Install the Codity GitHub App: https://github.com/apps/codity
#   2. (Optional) Restrict to specific repos in the App settings.
#
# The workflow runs on every pull-request and posts inline AI review
# comments directly on the PR diff.

name: Codity AI Review

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  pull-requests: write

jobs:
  codity-review:
    name: Codity AI Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for diff context

      - name: Install Codity CLI
        run: curl -fsSL https://cli.codity.ai/install.sh | sh

      - name: Run Codity review
        env:
          CODITY_ACCESS_TOKEN: ${{{{ secrets.CODITY_ACCESS_TOKEN }}}}
        run: codity review --staged
"""
        workflow_path.write_text(content, encoding="utf-8")
        return workflow_path

    def _write_gitlab_workflow(self, config: ProjectConfig, target: Path) -> Path:
        ci_path = target / ".gitlab-ci-codity.yml"
        content = f"""\
# Codity.ai AI Code Review — {config.name}
# Generated by specsmith (specsmith integrate codity)
#
# Prerequisites:
#   1. Configure a GitLab PAT: codity config set-pat --provider gitlab
#   2. Store it as CI/CD variable CODITY_GITLAB_PAT in GitLab settings.

stages:
  - review

codity-review:
  stage: review
  image: debian:bookworm-slim
  only:
    - merge_requests
  variables:
    CODITY_ACCESS_TOKEN: $CODITY_ACCESS_TOKEN
  script:
    - apt-get update -qq && apt-get install -y -qq curl
    - curl -fsSL https://cli.codity.ai/install.sh | sh
    - codity config set-pat --provider gitlab --token "$CODITY_GITLAB_PAT"
    - codity review --staged
"""
        ci_path.write_text(content, encoding="utf-8")
        return ci_path

    def _write_azure_workflow(self, config: ProjectConfig, target: Path) -> Path:
        pipelines_dir = target / ".azure-pipelines"
        pipelines_dir.mkdir(parents=True, exist_ok=True)
        pipeline_path = pipelines_dir / "codity-review.yml"
        content = f"""\
# Codity.ai AI Code Review — {config.name}
# Generated by specsmith (specsmith integrate codity)
#
# Prerequisites:
#   1. Configure an Azure DevOps PAT: codity config set-pat --provider azure
#   2. Store it as pipeline variable CODITY_AZURE_PAT (secret).

trigger: none

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

steps:
  - script: curl -fsSL https://cli.codity.ai/install.sh | sh
    displayName: Install Codity CLI

  - script: |
      codity config set-pat --provider azure --token "$(CODITY_AZURE_PAT)"
      codity review --staged
    displayName: Run Codity AI Review
    env:
      CODITY_ACCESS_TOKEN: $(CODITY_ACCESS_TOKEN)
"""
        pipeline_path.write_text(content, encoding="utf-8")
        return pipeline_path

    # ---- setup doc --------------------------------------------------

    def _write_setup_doc(self, config: ProjectConfig, target: Path, vcs: str) -> Path:
        docs_dir = target / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)
        doc_path = docs_dir / "codity-setup.md"

        pat_note = ""
        if vcs == "gitlab":
            pat_note = (
                "\n5. Set GitLab PAT: `codity config set-pat --provider gitlab`\n"
                "6. Add `CODITY_GITLAB_PAT` as a CI/CD variable in GitLab.\n"
            )
        elif vcs == "azure":
            pat_note = (
                "\n5. Set Azure DevOps PAT: `codity config set-pat --provider azure`\n"
                "6. Add `CODITY_AZURE_PAT` as a secret pipeline variable.\n"
            )

        content = f"""\
# Codity.ai Setup — {config.name}

> Generated by `specsmith integrate codity`.

## One-time setup checklist

1. Install Codity CLI:
   ```bash
   curl -fsSL https://cli.codity.ai/install.sh | sh
   ```
   Native Windows (PowerShell) is also supported via GitHub Releases
   (`codity-ai/codity-cli`), because the shell installer is Linux/macOS only:
   ```powershell
   # No official winget/scoop/choco package currently.
   $release = Invoke-RestMethod -Uri "https://api.github.com/repos/codity-ai/codity-cli/releases/latest"
   $version = $release.tag_name.TrimStart("v")
   $assetName = "codity_" + $version + "_windows_amd64.zip"
   $asset = $release.assets | Where-Object {{ $_.name -eq $assetName }} | Select-Object -First 1
   $zip = Join-Path $env:TEMP $asset.name
   $tmp = Join-Path $env:TEMP ("codity-install-" + [guid]::NewGuid().ToString())
   Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zip
   Expand-Archive -Path $zip -DestinationPath $tmp -Force
   New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\\.local\\bin" | Out-Null
   Copy-Item (Join-Path $tmp "codity.exe") "$env:USERPROFILE\\.local\\bin\\codity.exe" -Force
   ```

2. Authenticate:
   ```bash
   codity login   # opens browser — magic-link auth
   ```

3. Initialise in this project:
   ```bash
   codity init
   ```

4. (GitHub) Install the Codity GitHub App:
   <https://github.com/apps/codity>{pat_note}

## Daily usage

| Command | Effect |
|---|---|
| `codity review --staged` | AI review of staged changes |
| `codity scan --staged` | Security & quality scan of staged changes |
| `codity test-gen --staged` | Generate tests for staged changes |
| `codity doctor` | Health-check CLI + project config |

## Config location

`~/.codity/config.yaml` — or set `CODITY_ACCESS_TOKEN` env var to override.

## AGENTS.md rule

Projects with Codity configured SHOULD run `codity review --staged` before
any commit that touches production code. Treat HIGH-severity findings as
blocking; MEDIUM findings require inline acknowledgement.
"""
        doc_path.write_text(content, encoding="utf-8")
        return doc_path

    # ---- ledger append ----------------------------------------------

    def _append_ledger(self, target: Path, vcs: str) -> None:
        ledger = target / "LEDGER.md"
        if not ledger.exists():
            return
        entry = (
            "\n## TODO: Codity.ai Setup\n\n"
            "- [ ] Run `codity login` and complete browser auth\n"
            "- [ ] Run `codity init` in project root\n"
        )
        if vcs == "github":
            entry += "- [ ] Install Codity GitHub App: https://github.com/apps/codity\n"
            entry += (
                "- [ ] Add `CODITY_ACCESS_TOKEN` to repo secrets (optional — App handles auth)\n"
            )
        elif vcs == "gitlab":
            entry += (
                "- [ ] `codity config set-pat --provider gitlab` "
                "and add `CODITY_GITLAB_PAT` to CI/CD vars\n"
            )
        elif vcs == "azure":
            entry += (
                "- [ ] `codity config set-pat --provider azure` "
                "and add `CODITY_AZURE_PAT` to pipeline vars\n"
            )
        entry += "- [ ] Run `codity doctor` to verify setup\n"
        with ledger.open("a", encoding="utf-8") as f:
            f.write(entry)
