"""add_ai_regulation_requirements.py

Add AI regulation compliance requirements (REG domain) to all governance
files. Requirements sourced from BTWS 2027 Agentic AI Governance Report:
  - EU AI Act (Regulation (EU) 2024/1689) — GPAI obligations Aug 2025,
    high-risk conformity Aug 2026
  - NIST AI Risk Management Framework (July 2024)
  - OMB Memorandum M-24-10 (March 2024)
  - Colorado SB24-205 (effective Feb 2026)
  - FTC Operation AI Comply (Sept 2024)
  - California CPRA/ADMT (2025)
  - Utah SB149 (2024)

Starting ID: REQ-206. Safe to re-run (aborts if REQ-206 already exists).
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
START_ID = 206

# ---------------------------------------------------------------------------
# AI Regulation requirement definitions
# Each tuple: (domain_id, title, description, source_laws)
# ---------------------------------------------------------------------------
REG_REQUIREMENTS: list[tuple[str, str, str]] = [
    # --- Auditability & Logging ---
    (
        "REG-001",
        "Tamper-Evident Agent Action Log",
        "specsmith MUST maintain a tamper-evident, append-only agent action log "
        "capturing every governance decision, tool invocation, input, and output. "
        "The log chain MUST use SHA-256 chaining so any modification is detectable. "
        "Satisfies EU AI Act Art. 12 (logging obligations) and NIST AI RMF (GO-6).",
    ),
    (
        "REG-002",
        "Explanation Artifacts for Governance Decisions",
        "Every governance decision (preflight, verify, classify) MUST produce an "
        "'explanation artifact' recording: what data was used, which requirements "
        "were matched, why the decision was reached, and the confidence score. "
        "Satisfies EU AI Act Art. 13 (transparency), CFPB adverse-action requirements.",
    ),
    (
        "REG-003",
        "Action Log Replay and Export",
        "specsmith MUST support structured replay and export of agent action logs "
        "for external audit, regulatory submission, or incident investigation. "
        "Export format MUST be machine-readable (JSONL) and human-readable (Markdown). "
        "Satisfies OMB M-24-10 (AI use case inventories) and EU AI Act post-market monitoring.",
    ),
    # --- Human Oversight ---
    (
        "REG-004",
        "Human Escalation Threshold",
        "specsmith MUST provide a configurable human-escalation threshold. When "
        "preflight confidence is below the threshold, or when a destructive/release "
        "intent is detected, execution MUST pause and route to human review. "
        "Satisfies NIST AI RMF (GO-4), OMB M-24-10 human-in-the-loop requirements.",
    ),
    (
        "REG-005",
        "Emergency Kill-Switch and Circuit-Breaker",
        "specsmith MUST implement an emergency kill-switch that immediately halts "
        "agent activity when: (a) the user invokes a stop command, (b) an anomaly "
        "detector triggers, or (c) the retry budget is exhausted. The kill-switch "
        "MUST be reachable from both the CLI and the REST API. "
        "Satisfies EU AI Act Art. 14 (human oversight), NIST AI RMF.",
    ),
    (
        "REG-006",
        "Post-Market Behavioral Monitoring and Alerting",
        "specsmith MUST monitor agent behavior across sessions and alert when "
        "anomalous patterns are detected: unexpected confidence regression, "
        "unusual tool usage rates, or systematic requirement mismatches. "
        "Satisfies EU AI Act Art. 72 (post-market monitoring) and OMB M-24-10.",
    ),
    # --- Rollback and Recovery ---
    (
        "REG-007",
        "One-Click Rollback for File-Modifying Actions",
        "Every agent action that modifies governance files MUST create a "
        "timestamped backup before overwriting, and MUST expose a rollback "
        "command that restores the pre-action state. "
        "Satisfies NIST AI GenAI Profile (rollback and compensation), CFPB.",
    ),
    (
        "REG-008",
        "Safe Append-Only Write for New Governance Entries",
        "All new entries appended to governance files (LEDGER.md, REQUIREMENTS.md, "
        "TESTS.md) MUST use append-only mode — never truncating or overwriting "
        "existing content. Protects against data loss from agent errors. "
        "Satisfies EU AI Act technical controls and data integrity requirements.",
    ),
    # --- Transparency and Disclosure ---
    (
        "REG-009",
        "AI Disclosure Metadata in Agent Outputs",
        "Outputs generated by specsmith agents MUST include AI disclosure metadata "
        "when surfaced to end-users: which model was used, provider, confidence "
        "level, and whether the output was governance-gated. "
        "Satisfies FTC Operation AI Comply, Utah SB149 (2024) disclosure requirements.",
    ),
    (
        "REG-010",
        "Regulatory Compliance Export Report",
        "specsmith MUST generate a structured compliance export report covering: "
        "AI system inventory, risk classification, human oversight controls, "
        "audit log summary, and incident history. "
        "Satisfies OMB M-24-10, Colorado SB24-205 impact assessments, EU AI Act technical docs.",
    ),
    # --- Risk Classification ---
    (
        "REG-011",
        "Agent Risk Classification Before Deployment",
        "Before activating a governance profile or agent session, specsmith MUST "
        "classify the intended use case against EU AI Act risk tiers (prohibited, "
        "high-risk Annex III, GPAI systemic-risk, or minimal-risk). "
        "High-risk use cases MUST require additional confirmation. "
        "Satisfies EU AI Act Art. 6 risk-based approach.",
    ),
    (
        "REG-012",
        "Least-Privilege Agent Permissions",
        "Every agent session MUST operate with the minimum permissions required. "
        "Agent capabilities MUST be explicitly declared, and sensitive operations "
        "(commit, push, create PR, external calls) MUST be individually gated. "
        "Satisfies EU AI Act agent registration, NIST AI RMF least-privilege principle.",
    ),
    # --- Self-Optimization Governance ---
    (
        "REG-013",
        "Self-Optimization Bounded by Iteration Budget",
        "All self-improvement loops (agent improve, eval harness, continuous learning) "
        "MUST be bounded by a configurable iteration budget. Unbounded recursion or "
        "runaway optimisation MUST be prevented. "
        "Satisfies EU AI Act systemic risk controls (GPAISR) and credit spend governance.",
    ),
    (
        "REG-014",
        "Local-First Model Routing for Governance Tasks",
        "Governance classification tasks (preflight, verify, classify_intent) MUST "
        "default to a local Ollama model (zero cloud cost) and only escalate to "
        "cloud APIs when local confidence is below threshold. "
        "Reduces credit spend and avoids unnecessary data transfer to third parties.",
    ),
    # --- Data Protection ---
    (
        "REG-015",
        "Policy Guardrails at the Interface Layer",
        "specsmith MUST enforce allow/deny lists for tool categories and data access "
        "patterns at the agent interface layer — not just within prompts. "
        "Agents MUST NOT access live production databases or unmanaged data sources. "
        "Satisfies EU AI Act technical controls, California ADMT data governance requirements.",
    ),
]


def main() -> None:
    req_json_path = REPO / ".specsmith" / "requirements.json"
    test_json_path = REPO / ".specsmith" / "testcases.json"
    work_json_path = REPO / ".specsmith" / "workitems.json"
    req_md_path = REPO / "docs" / "REQUIREMENTS.md"
    tests_md_path = REPO / "docs" / "TESTS.md"

    existing = json.loads(req_json_path.read_text(encoding="utf-8"))
    if any(r["id"] == f"REQ-{START_ID:03d}" for r in existing):
        print(f"REQ-{START_ID:03d} already exists — migration already applied, aborting.")
        return

    existing_tests = json.loads(test_json_path.read_text(encoding="utf-8"))
    existing_work = json.loads(work_json_path.read_text(encoding="utf-8"))

    new_reqs, new_tests, new_work = [], [], []
    req_md_lines, test_md_lines = [], []

    for i, (domain_id, title, description) in enumerate(REG_REQUIREMENTS):
        n = START_ID + i
        req_id = f"REQ-{n:03d}"
        test_id = f"TEST-{n:03d}"
        work_id = f"WORK-{n:03d}"

        new_reqs.append({
            "id": req_id,
            "title": title,
            "description": description,
            "source": f"BTWS-2027 AI Governance Report (EU AI Act / NIST / OMB) [{domain_id}]",
            "status": "defined",
        })
        new_tests.append({
            "id": test_id,
            "title": title,
            "description": description,
            "requirement_id": req_id,
            "type": "compliance",
            "verification_method": "evaluator",
            "input": {},
            "expected_behavior": {},
            "confidence": 1.0,
        })
        new_work.append({
            "id": work_id,
            "requirement_id": req_id,
            "test_case_ids": [test_id],
            "status": "pending",
            "attempts": 0,
            "max_attempts": 3,
            "priority": "high",
        })

        req_md_lines += [
            f"\n## {n}. {title}",
            f"- **ID:** {req_id}",
            f"- **Title:** {title}",
            f"- **Description:** {description}",
            f"- **Source:** BTWS-2027 AI Governance Report [{domain_id}]",
            "- **Status:** defined",
        ]
        test_md_lines += [
            f"\n## {test_id}. {title}",
            f"- **ID:** {test_id}",
            f"- **Title:** {title}",
            f"- **Description:** {description}",
            f"- **Requirement ID:** {req_id}",
            "- **Type:** compliance",
            "- **Verification Method:** evaluator",
            "- **Input:** {}",
            "- **Expected Behavior:** {}",
            "- **Confidence:** 1.0",
        ]

    req_json_path.write_text(
        json.dumps(existing + new_reqs, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    test_json_path.write_text(
        json.dumps(existing_tests + new_tests, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    work_json_path.write_text(
        json.dumps(existing_work + new_work, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    req_md_path.write_text(
        req_md_path.read_text(encoding="utf-8") + "\n" + "\n".join(req_md_lines) + "\n",
        encoding="utf-8",
    )
    tests_md_path.write_text(
        tests_md_path.read_text(encoding="utf-8") + "\n" + "\n".join(test_md_lines) + "\n",
        encoding="utf-8",
    )

    total = len(REG_REQUIREMENTS)
    end_id = START_ID + total - 1
    print(f"AI regulation requirements added: REQ-{START_ID:03d}..REQ-{end_id:03d} ({total} reqs)")
    print(f"Updated: docs/REQUIREMENTS.md, docs/TESTS.md, requirements.json, testcases.json, workitems.json")


if __name__ == "__main__":
    main()
