import json

REQS = [
    {
        "ID": "REQ-001",
        "Title": "Specsmith Must Govern Itself",
        "Description": "Specsmith must govern its own governance layer and use it for all changes.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-002",
        "Title": "Governance Files Must Be Owned by Specsmith",
        "Description": "Only Specsmith may create, update, or delete the human‑readable governance files `ARCHITECTURE.md`, `REQUIREMENTS.md`, `TESTS.md`, and `LEDGER.md`.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-003",
        "Title": "Machine State Must Reflect Governance State",
        "Description": "Every machine‑readable state file under `.specsmith/` must be derived from its corresponding human‑readable governance file and remain in sync.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-004",
        "Title": "Requirements Must Be Derived from Architecture",
        "Description": "Specsmith must parse `ARCHITECTURE.md` to produce initial requirements.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-005",
        "Title": "Requirement IDs Must Be Stable",
        "Description": "Once assigned, a requirement ID must never change or be reused.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-006",
        "Title": "Preflight Validation Must Be Performed",
        "Description": "Before any governance action, the system must validate inputs and produce structured output with required fields.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-007",
        "Title": "Test Cases Must Be Generated from Requirements",
        "Description": "For each requirement, Specsmith must create or link a test case that can prove the requirement.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-008",
        "Title": "Each Requirement Must Link to At Least One Test",
        "Description": "Each requirement must be traceable to at least one test case.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-009",
        "Title": "Work Items Must Be Created for Accepted Requirements",
        "Description": "When a requirement is accepted, a unique work item must be created.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-010",
        "Title": "Requirements Must Include Priority and Status",
        "Description": "Each requirement record must contain `priority` and `status` attributes.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-011",
        "Title": "Verification Must Include Confidence Scoring",
        "Description": "Every verification run must produce a numeric confidence score along with pass/fail.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-012",
        "Title": "Equilibrium Must Be Reached Before Finalizing",
        "Description": "A work item may be marked finished only when its verification confidence meets or exceeds the configured threshold and no contradictions remain.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-013",
        "Title": "Retry Recommendations Must Be Provided",
        "Description": "Specsmith must output retry recommendations when verification fails.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-014",
        "Title": "Retries Must Be Bounded",
        "Description": "Each retry mechanism may not exceed a fixed maximum number of attempts.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-015",
        "Title": "Every Governance Action Must Record a Ledger Event",
        "Description": "All changes are logged to `LEDGER.md` and `.specsmith/ledger.jsonl` with timestamp and type.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-016",
        "Title": "Trace Chain Must Be Tamper‑Evident",
        "Description": "The trace chain must use chained cryptographic hashes to provide tamper evidence.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-017",
        "Title": "OpenCode Must Own Execution and Tools",
        "Description": "All filesystem operations and tool executions are performed by OpenCode.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-018",
        "Title": "Specsmith Core Must Be Integration‑Agnostic",
        "Description": "The core logic must run without dependency on any implementation.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-019",
        "Title": "Verification Must Evaluate Changed Files",
        "Description": "Verification must analyze file changes.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-020",
        "Title": "Verification Must Evaluate Diff Relevance",
        "Description": "Verification must ignore irrelevant diffs.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-021",
        "Title": "Verification Must Evaluate Test Results",
        "Description": "Verification must compare outputs.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-022",
        "Title": "Verification Must Evaluate Contradictions and Uncertainty",
        "Description": "Identify contradictions.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-023",
        "Title": "Requirement Schema Must Include Source Location, Type, Priority, Confidence, Status, and Timestamps",
        "Description": "Schema must include these.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-024",
        "Title": "Test Case Model Must Include Required Fields",
        "Description": "All test case records must contain required fields.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-025",
        "Title": "Work Item Model Must Include Required Fields",
        "Description": "Each work item record must contain required fields.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-026",
        "Title": "Preflight Output Schema Must Include Decision, Work Item ID, Priority, Requirement IDs, Test Case IDs, Confidence Target",
        "Description": "Structured preflight output.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-027",
        "Title": "Verification Input Must Include Diffs, Tests, Logs, and Changed Files",
        "Description": "Input contains diffs, logs.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-028",
        "Title": "Retry Strategy Mapping Must Be Defined",
        "Description": "Map strategies.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-029",
        "Title": "Integration Adapter Interface Must Provide Capabilities",
        "Description": "Provide adapter.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-030",
        "Title": "Specsmith CLI Commands Must Be Explicitly Defined",
        "Description": "Expose commands.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-031",
        "Title": "Sequencing Rules Must Enforce Valid States",
        "Description": "Bootstrap sequencing.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-032",
        "Title": "Configuration Settings for Optional Features",
        "Description": "Read config.",
        "Source": ".specsmith/config.yml, ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-033",
        "Title": "Default Enablement of Optional Features",
        "Description": "Enabled by default.",
        "Source": ".specsmith/config.yml, ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-034",
        "Title": "Evidence ZIP Archive Generation",
        "Description": "Generate evidence ZIP.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-035",
        "Title": "Evidence Manifest Generation",
        "Description": "Generate evidence manifest.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-036",
        "Title": "Per‑File SHA‑256 Hashing in Evidence",
        "Description": "Hash every file.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-037",
        "Title": "Final Evidence ZIP SHA‑256 Hash",
        "Description": "Hash final zip.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-038",
        "Title": "Author/Owner Metadata Capture",
        "Description": "Capture metadata.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-039",
        "Title": "Git Commit Metadata Inclusion",
        "Description": "Include git commit.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-040",
        "Title": "Ledger Reference Inclusion",
        "Description": "Reference ledger.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-041",
        "Title": "Trusted Timestamp Token Support",
        "Description": "Include timestamp token.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-042",
        "Title": "Legal/IP Disclaimer Requirement",
        "Description": "Provide disclaimer.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-043",
        "Title": "Ledger Event Hash Chaining",
        "Description": "Chain events.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-044",
        "Title": "Ledger Event on Work Proposal",
        "Description": "Create event on proposal.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-045",
        "Title": "Ledger Event on Work Completion",
        "Description": "Create event on completion.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-046",
        "Title": "README.md Generation and Synchronization",
        "Description": "Generate README.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-047",
        "Title": "CHANGELOG.md Generation and Synchronization",
        "Description": "Generate CHANGELOG.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-048",
        "Title": "Keep a Changelog Compliance",
        "Description": "Compliance.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-049",
        "Title": "Semantic Versioning Support",
        "Description": "Support semantic versioning.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-050",
        "Title": "Guided Version Bump Workflow",
        "Description": "Guided version bump.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-051",
        "Title": "Guided Release Strategy Workflow",
        "Description": "Guided release strategy.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-052",
        "Title": "Guided Branching Strategy Workflow",
        "Description": "Guided branching strategy.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-053",
        "Title": "Default GitFlow Branching Model",
        "Description": "Default GitFlow.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-054",
        "Title": "Guided Branching Modification",
        "Description": "Guided branching modification.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-055",
        "Title": "GitHub License Generation",
        "Description": "Generate GitHub license.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-056",
        "Title": "Commercial License Drafting Guidance",
        "Description": "Draft commercial license.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-057",
        "Title": "Local Git Commit After Work",
        "Description": "Commit after work.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-058",
        "Title": "Confidence Threshold Configuration",
        "Description": "Configure threshold.",
        "Source": ".specsmith/config.yml, ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-059",
        "Title": "Iteration Continuation Until Threshold",
        "Description": "Continue until threshold.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-060",
        "Title": "Indefinite Iteration Default",
        "Description": "Use indefinite iteration.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-061",
        "Title": "Max Iterations Configuration",
        "Description": "Configure max iterations.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-062",
        "Title": "Token/Cost/Time Limits Configuration",
        "Description": "Configure token/cost/time limits.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-063",
        "Title": "Stop‑and‑Align Behavior",
        "Description": "Stop when confidence cannot improve.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
    {
        "ID": "REQ-064",
        "Title": "Interactive Correction Workflow",
        "Description": "Provide interactive correction workflow.",
        "Source": "ARCHITECTURE.md",
        "Status": "defined",
    },
]

with open(".specsmith/requirements.json", "w", encoding="utf-8") as f:
    json.dump(REQS, f, indent=2)
print("Rebuilt JSON", len(REQS))
