"""Rename canonical test-spec governance file from TEST_SPEC.md to TESTS.md.

Walks the project tree, rewriting any in-file references to the legacy names
(`TEST_SPEC.md`, `TEST-SPECS.md`, `TEST-SPEC.md`) to the new canonical
`TESTS.md`. Skips historical evidence patches under `.specsmith/runs/` and the
ctags `tags` file (binary-ish, regenerated by ctags itself).

Run from the repo root:

    py scripts/rename_test_spec.py
"""

from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Skip these directories entirely.
SKIP_DIRS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".pytest_tmp",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
}

# Skip these specific files (historical evidence; do not rewrite).
SKIP_RELATIVE_FILES = {
    Path(".specsmith") / "runs" / "WI-NEXUS-001" / "diff.patch",
    Path(".specsmith") / "runs" / "WI-NEXUS-002" / "diff.patch",
    Path(".specsmith") / "runs" / "WI-NEXUS-003" / "diff.patch",
    Path("tags"),
    Path("scripts") / "rename_test_spec.py",  # don't rewrite this script
}

# Only rewrite text-ish files.
TEXT_SUFFIXES = {
    ".py",
    ".md",
    ".yml",
    ".yaml",
    ".toml",
    ".json",
    ".jsonl",
    ".j2",
    ".rst",
    ".txt",
    ".cfg",
    ".ini",
    ".ps1",
    ".cmd",
    ".sh",
}

REPLACEMENTS = (
    ("TEST_SPEC.md", "TESTS.md"),
    ("TEST-SPECS.md", "TESTS.md"),
    ("TEST-SPEC.md", "TESTS.md"),
)


def _should_skip(rel: Path) -> bool:
    parts = set(rel.parts)
    if parts & SKIP_DIRS:
        return True
    return rel in SKIP_RELATIVE_FILES


def _rewrite_file(path: Path) -> bool:
    try:
        original = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return False
    new = original
    for old, replacement in REPLACEMENTS:
        new = new.replace(old, replacement)
    if new != original:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def main() -> None:
    rewritten: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        # Skip ignored directories in-place.
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fname in filenames:
            p = Path(dirpath) / fname
            rel = p.relative_to(ROOT)
            if _should_skip(rel):
                continue
            if p.suffix.lower() not in TEXT_SUFFIXES:
                continue
            if _rewrite_file(p):
                rewritten.append(rel)

    # Now physically move the files if they still exist under the legacy name.
    for legacy_rel in (Path("TEST_SPEC.md"), Path("docs") / "TEST_SPEC.md"):
        legacy = ROOT / legacy_rel
        if legacy.is_file():
            new_path = legacy.with_name("TESTS.md")
            if new_path.exists():
                # Prefer the rewritten content of legacy if both exist.
                new_path.write_text(legacy.read_text(encoding="utf-8"), encoding="utf-8")
                legacy.unlink()
            else:
                legacy.rename(new_path)
            rewritten.append(legacy_rel)

    print(f"Rewrote/renamed {len(rewritten)} file(s).")
    for r in rewritten:
        print(f"  - {r}")


if __name__ == "__main__":
    main()
