# SPDX-License-Identifier: MIT
# Copyright (c) 2026 BitConcepts, LLC. All rights reserved.
"""M001 — Governance YAML migration.

Copies docs/governance/*.md content into .specsmith/governance/*.yaml as
structured YAML documents. The MD files are left intact as read-only views.

This is non-destructive: it adds new files without removing existing ones.
"""

from __future__ import annotations

import re
from pathlib import Path

from specsmith.migrations import Migration, MigrationResult


class GovernanceYamlMigration(Migration):
    version = 1
    title = "Migrate docs/governance/*.md → .specsmith/governance/*.yaml"
    description = (
        "Creates structured YAML governance files in .specsmith/governance/ "
        "from the existing Markdown governance files. The MD files are kept "
        "as generated views. specsmith will prefer YAML when both exist."
    )

    def run(self, root: Path, *, dry_run: bool = False) -> MigrationResult:
        result = MigrationResult(version=self.version, title=self.title, dry_run=dry_run)
        gov_dir = root / ".specsmith" / "governance"

        # Map from MD filename → YAML filename + kind
        migrations_map = [
            ("RULES.md", "rules.yaml", "rules"),
            ("EPISTEMIC-AXIOMS.md", "axioms.yaml", "axioms"),
            ("ROLES.md", "roles.yaml", "roles"),
            ("LIFECYCLE.md", "lifecycle.yaml", "lifecycle"),
            ("CONTEXT-BUDGET.md", "context-budget.yaml", "context-budget"),
            ("VERIFICATION.md", "verification.yaml", "verification"),
            ("DRIFT-METRICS.md", "drift-metrics.yaml", "drift-metrics"),
            ("SESSION-PROTOCOL.md", "session-protocol.yaml", "session-protocol"),
        ]

        if not dry_run:
            gov_dir.mkdir(parents=True, exist_ok=True)

        for md_name, yaml_name, kind in migrations_map:
            md_path = root / "docs" / "governance" / md_name
            yaml_path = gov_dir / yaml_name

            if not md_path.exists():
                continue  # Skip if source doesn't exist

            if yaml_path.exists():
                continue  # Already migrated — skip

            if dry_run:
                result.files_created.append(f".specsmith/governance/{yaml_name}")
                continue

            # Convert MD to structured YAML
            content = md_path.read_text(encoding="utf-8", errors="replace")
            yaml_content = _md_to_yaml(kind, content, md_name)

            yaml_path.write_text(yaml_content, encoding="utf-8")
            result.files_created.append(f".specsmith/governance/{yaml_name}")

        if dry_run:
            n = len(result.files_created)
            result.message = f"Would create {n} governance YAML file(s) in .specsmith/governance/"
        elif result.files_created:
            result.message = (
                f"Created {len(result.files_created)} governance YAML file(s). "
                "Original MD files kept as read-only views."
            )
        else:
            result.message = "All governance YAML files already present — nothing to do."

        return result


def _md_to_yaml(kind: str, md_content: str, source_file: str) -> str:
    """Convert Markdown governance file to structured YAML."""
    import yaml as _yaml

    if kind == "rules":
        return _rules_md_to_yaml(md_content, source_file)
    else:
        # Generic: store content as-is with metadata
        data = {
            "kind": kind,
            "source_md": f"docs/governance/{source_file}",
            "generated_by": "specsmith migrate (m001)",
            "content": md_content,
        }
        return f"# Generated by specsmith migrate m001\n# Edit this file; original MD kept as view.\n\n" + _yaml.dump(
            data, default_flow_style=False, allow_unicode=True
        )


def _rules_md_to_yaml(md_content: str, source_file: str) -> str:
    """Parse H1-H22 rules from RULES.md into structured YAML."""
    import yaml as _yaml

    rules = []
    # Parse ### HN — Title sections
    pattern = re.compile(
        r"### (H\d+) \u2014 (.+?)\n(.*?)(?=\n### H|\Z)",
        re.DOTALL
    )
    for match in pattern.finditer(md_content):
        rule_id = match.group(1)
        name = match.group(2).strip()
        body = match.group(3).strip()
        rules.append({
            "id": rule_id,
            "name": name,
            "description": body[:500] if body else "",
        })

    data = {
        "kind": "rules",
        "source_md": f"docs/governance/{source_file}",
        "generated_by": "specsmith migrate (m001)",
        "rules": rules if rules else [{"note": "Could not parse rules — see source MD"}],
    }
    return (
        "# specsmith governance rules — structured YAML\n"
        "# Generated by: specsmith migrate run --version 1\n"
        "# Source: docs/governance/RULES.md\n"
        "# Edit this file; original MD kept as read-only view.\n\n"
        + _yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)
    )
