from __future__ import annotations

import json
import re
import subprocess
import zipfile
from pathlib import Path
from typing import Any

import click

PROJECT_TYPES = (
    "python-cli",
    "fastapi",
    "react",
    "typescript",
    "rust",
    "go",
    "ai-agent",
    "docs-only",
)
MODES = ("lite", "team", "regulated")
AGENT_CHOICES = ("claude-code", "cursor", "warp", "copilot", "none")
CI_CHOICES = ("github-actions", "none")

LITE_FILES = (
    "AGENTS.md",
    "LEDGER.md",
    "docs/REQUIREMENTS.md",
    "docs/TESTS.md",
    "docs/ARCHITECTURE.md",
)
TEAM_EXTRA_FILES = (
    "docs/governance/RULES.md",
    "docs/governance/SESSION-PROTOCOL.md",
    "docs/governance/LIFECYCLE.md",
    "docs/governance/ROLES.md",
)
REGULATED_EXTRA_FILES = (
    "docs/governance/CONTEXT-BUDGET.md",
    "docs/governance/VERIFICATION.md",
    "docs/governance/DRIFT-METRICS.md",
)

REQ_ID_RE = re.compile(r"\b(REQ-(?:[A-Z][A-Z0-9_]*-)?\d+)\b")
TEST_ID_RE = re.compile(r"\b(TEST-(?:[A-Z][A-Z0-9_]*-)?\d+[a-z]*)\b")


def _parse_multi(raw: str, allowed: tuple[str, ...]) -> list[str]:
    picks = [chunk.strip() for chunk in raw.split(",") if chunk.strip()]
    deduped: list[str] = []
    for item in picks:
        if item in allowed and item not in deduped:
            deduped.append(item)
    return deduped


def _write_if_missing(path: Path, content: str) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _ensure_governance_mode_files(root: Path, mode: str) -> list[str]:
    created: list[str] = []
    if _write_if_missing(root / "AGENTS.md", "# AGENTS.md\n\nGovernance hub.\n"):
        created.append("AGENTS.md")
    if _write_if_missing(root / "LEDGER.md", "# Ledger\n\nNo entries yet.\n"):
        created.append("LEDGER.md")
    if _write_if_missing(
        root / "docs" / "ARCHITECTURE.md",
        "# Architecture\n\nGenerated by specsmith quickstart.\n",
    ):
        created.append("docs/ARCHITECTURE.md")

    req_path = root / "docs" / "REQUIREMENTS.md"
    test_path = root / "docs" / "TESTS.md"
    if _write_if_missing(
        req_path,
        (
            "# Requirements\n\n"
            "## REQ-QUICKSTART-001: Sample requirement\n"
            "- **ID:** REQ-QUICKSTART-001\n"
            "- **Description:** The generated quickstart project SHALL validate setup.\n"
            "- **Status:** defined\n"
        ),
    ):
        created.append("docs/REQUIREMENTS.md")
    if _write_if_missing(
        test_path,
        (
            "# Tests\n\n"
            "## TEST-QUICKSTART-001\n"
            "- **ID:** TEST-QUICKSTART-001\n"
            "- **Description:** Validate quickstart setup and governance files.\n"
            "- **Requirement ID:** REQ-QUICKSTART-001\n"
            "- **Status:** Pending\n"
        ),
    ):
        created.append("docs/TESTS.md")

    if mode in ("team", "regulated"):
        for rel in TEAM_EXTRA_FILES:
            if _write_if_missing(
                root / rel,
                f"# {Path(rel).stem}\n\nGenerated by expand/team mode.\n",
            ):
                created.append(rel)
    if mode == "regulated":
        for rel in REGULATED_EXTRA_FILES:
            if _write_if_missing(
                root / rel,
                f"# {Path(rel).stem}\n\nGenerated by expand/regulated mode.\n",
            ):
                created.append(rel)
    return created


def _load_json_list(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return []
    if not isinstance(payload, list):
        return []
    out: list[dict[str, Any]] = []
    for row in payload:
        if isinstance(row, dict):
            out.append(row)
    return out


def _collect_sources(root: Path, kind: str) -> list[Path]:
    patterns = {
        "spec-kit": ("spec-kit*.md", "specs/**/*.md"),
        "openspec": ("openspec*.md", "open-spec*.md", "spec/**/*.md", "docs/**/*.md"),
        "bmad": ("bmad*.md", "docs/**/*.md", "**/*bmad*.md"),
    }
    chosen = patterns[kind]
    candidates: list[Path] = []
    for pat in chosen:
        candidates.extend(root.glob(pat))
    filtered: list[Path] = []
    for candidate in candidates:
        if not candidate.is_file():
            continue
        if ".git" in candidate.parts or ".specsmith" in candidate.parts:
            continue
        if candidate not in filtered:
            filtered.append(candidate)
    if filtered:
        return filtered
    fallback = [
        p
        for p in root.rglob("*.md")
        if p.is_file() and ".git" not in p.parts and ".specsmith" not in p.parts
    ]
    return fallback[:50]


def _import_from_kind(
    root: Path,
    kind: str,
    dry_run: bool,
) -> dict[str, Any]:
    sources = _collect_sources(root, kind)
    req_rows: list[dict[str, Any]] = []
    test_rows: list[dict[str, Any]] = []
    req_seen: set[str] = set()
    test_seen: set[str] = set()
    req_counter = 1
    test_counter = 1

    for src in sources:
        text = src.read_text(encoding="utf-8", errors="ignore")
        req_ids = list(REQ_ID_RE.findall(text))
        test_ids = list(TEST_ID_RE.findall(text))
        if not req_ids and text.strip():
            req_ids = [f"REQ-{kind.upper().replace('-', '_')}-{req_counter:03d}"]
            req_counter += 1
        for req_id in req_ids:
            if req_id in req_seen:
                continue
            req_seen.add(req_id)
            req_rows.append(
                {
                    "id": req_id,
                    "title": req_id,
                    "description": f"Imported from {src.name}",
                    "source": str(src.relative_to(root)),
                    "status": "imported",
                }
            )
        if not test_ids and req_ids:
            test_ids = [f"TEST-{kind.upper().replace('-', '_')}-{test_counter:03d}"]
            test_counter += 1
        for test_id in test_ids:
            if test_id in test_seen:
                continue
            test_seen.add(test_id)
            req_link = req_ids[0] if req_ids else ""
            test_rows.append(
                {
                    "id": test_id,
                    "title": test_id,
                    "description": f"Imported from {src.name}",
                    "requirement_id": req_link,
                    "type": "imported",
                    "verification_method": "review",
                    "input": {},
                    "expected_behavior": {},
                    "confidence": 1.0,
                }
            )

    state_dir = root / ".specsmith"
    req_json = state_dir / "requirements.json"
    test_json = state_dir / "testcases.json"
    report = {
        "kind": kind,
        "sources": [str(p.relative_to(root)) for p in sources],
        "requirements": len(req_rows),
        "tests": len(test_rows),
        "dry_run": dry_run,
        "requirements_path": str(req_json),
        "testcases_path": str(test_json),
    }
    if not dry_run:
        state_dir.mkdir(parents=True, exist_ok=True)
        req_json.write_text(json.dumps(req_rows, indent=2), encoding="utf-8")
        test_json.write_text(json.dumps(test_rows, indent=2), encoding="utf-8")
        report_path = state_dir / f"import-report-{kind}.json"
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        report["report_path"] = str(report_path)
    return report


def _export_payload(root: Path) -> dict[str, Any]:
    from specsmith.auditor import run_audit

    requirements = _load_json_list(root / ".specsmith" / "requirements.json")
    tests = _load_json_list(root / ".specsmith" / "testcases.json")
    workitems = _load_json_list(root / ".specsmith" / "workitems.json")
    audit_report = run_audit(root)
    return {
        "requirements": requirements,
        "tests": tests,
        "workitems": workitems,
        "audit": {
            "healthy": audit_report.healthy,
            "passed": audit_report.passed,
            "failed": audit_report.failed,
            "results": [
                {"name": r.name, "passed": r.passed, "message": r.message}
                for r in audit_report.results
            ],
        },
    }


def _to_markdown_export(payload: dict[str, Any]) -> str:
    reqs = payload["requirements"]
    tests = payload["tests"]
    wis = payload["workitems"]
    audit = payload["audit"]
    lines = [
        "# specsmith export",
        "",
        f"- Requirements: {len(reqs)}",
        f"- Tests: {len(tests)}",
        f"- Work items: {len(wis)}",
        f"- Audit: {'healthy' if audit['healthy'] else 'issues'}",
        "",
        "## Requirements",
    ]
    for req in reqs[:100]:
        lines.append(f"- {req.get('id', '?')}: {req.get('title', '')}")
    lines.append("")
    lines.append("## Tests")
    for test in tests[:100]:
        lines.append(f"- {test.get('id', '?')} -> {test.get('requirement_id', '') or 'unmapped'}")
    lines.append("")
    lines.append("## Audit findings")
    for row in audit["results"][:100]:
        icon = "✓" if row["passed"] else "✗"
        lines.append(f"- {icon} {row['name']}: {row['message']}")
    lines.append("")
    return "\n".join(lines) + "\n"


def _parse_issue_plan(path: Path) -> list[str]:
    titles: list[str] = []
    if not path.is_file():
        return titles
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("- [ ] "):
            titles.append(stripped.removeprefix("- [ ] ").strip())
    return [title for title in titles if title]


def _gh_open_issue_titles(repo: str) -> set[str]:
    cmd = [
        "gh",
        "issue",
        "list",
        "-R",
        repo,
        "--state",
        "open",
        "--limit",
        "200",
        "--json",
        "title",
    ]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return set()
    if result.returncode != 0:
        return set()
    try:
        payload = json.loads(result.stdout)
    except ValueError:
        return set()
    if not isinstance(payload, list):
        return set()
    titles: set[str] = set()
    for row in payload:
        if isinstance(row, dict) and row.get("title"):
            titles.add(str(row["title"]).strip().lower())
    return titles


def _calculate_trace_score(root: Path) -> dict[str, Any]:
    requirements = _load_json_list(root / ".specsmith" / "requirements.json")
    tests = _load_json_list(root / ".specsmith" / "testcases.json")
    workitems = _load_json_list(root / ".specsmith" / "workitems.json")

    req_ids = {str(req.get("id", "")) for req in requirements if req.get("id")}
    tested_req_ids = {
        str(test.get("requirement_id", "")) for test in tests if test.get("requirement_id")
    }
    req_with_tests = len(req_ids & tested_req_ids)
    req_with_work = 0
    for req in requirements:
        current_id = str(req.get("id", ""))
        if not current_id:
            continue
        if any(current_id in (wi.get("requirement_ids") or []) for wi in workitems):
            req_with_work += 1

    verified_work = sum(1 for wi in workitems if bool(wi.get("verified")))
    mapped_tests = sum(1 for test in tests if str(test.get("requirement_id", "")) in req_ids)
    orphan_tests = [
        str(test.get("id", "?"))
        for test in tests
        if str(test.get("requirement_id", "")) not in req_ids
    ]
    orphan_requirements = [req for req in req_ids if req not in tested_req_ids]
    stale_requirements = [
        str(req.get("id", "?"))
        for req in requirements
        if str(req.get("status", "defined")).lower() in {"defined", "draft"}
    ]

    req_total = max(len(req_ids), 1)
    wi_total = max(len(workitems), 1)
    test_total = max(len(tests), 1)

    metrics = {
        "requirements_with_tests": round((req_with_tests / req_total) * 100, 2),
        "requirements_with_work_items": round((req_with_work / req_total) * 100, 2),
        "work_items_with_verification": round((verified_work / wi_total) * 100, 2),
        "tests_mapped_to_requirements": round((mapped_tests / test_total) * 100, 2),
        "orphan_penalty": round(
            max(0.0, 100.0 - ((len(orphan_tests) + len(orphan_requirements)) * 10.0)),
            2,
        ),
    }
    score = round(sum(metrics.values()) / len(metrics), 2)
    recommendations: list[str] = []
    if orphan_tests:
        recommendations.append("Map orphan tests to requirement IDs.")
    if orphan_requirements:
        recommendations.append("Add tests for orphan requirements.")
    if stale_requirements:
        recommendations.append("Review stale requirements that remain in defined/draft state.")
    if not recommendations:
        recommendations.append(
            "Traceability coverage is healthy. Maintain current mapping discipline."
        )
    return {
        "score": score,
        "metrics": metrics,
        "counts": {
            "requirements": len(requirements),
            "tests": len(tests),
            "work_items": len(workitems),
            "orphan_tests": len(orphan_tests),
            "orphan_requirements": len(orphan_requirements),
            "stale_requirements": len(stale_requirements),
        },
        "orphan_tests": orphan_tests,
        "orphan_requirements": orphan_requirements,
        "stale_requirements": stale_requirements,
        "recommendations": recommendations,
    }


def _collect_changed_files(root: Path) -> list[str]:
    cmd = ["git", "--no-pager", "-C", str(root), "diff", "--name-only", "HEAD"]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except OSError:
        return []
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _drift_report(root: Path) -> dict[str, Any]:
    requirements = _load_json_list(root / ".specsmith" / "requirements.json")
    tests = _load_json_list(root / ".specsmith" / "testcases.json")
    workitems = _load_json_list(root / ".specsmith" / "workitems.json")
    changed = _collect_changed_files(root)
    req_ids = {str(req.get("id", "")) for req in requirements if req.get("id")}
    mapped_test_req_ids = {
        str(test.get("requirement_id", "")) for test in tests if test.get("requirement_id")
    }
    changed_code = [path for path in changed if path.startswith(("src/", "app/", "lib/"))]
    changed_without_req = bool(changed_code) and not bool(req_ids)
    req_without_changes = bool(req_ids) and not bool(changed_code)
    changed_without_tests = bool(changed_code) and not bool(mapped_test_req_ids)
    tests_not_mapped = [
        str(test.get("id", "?")) for test in tests if not test.get("requirement_id")
    ]
    work_item_intents = [str(wi.get("intent", "")) for wi in workitems if wi.get("intent")]

    findings: list[str] = []
    if changed_without_req:
        findings.append("Changed code detected without any linked requirements.")
    if req_without_changes:
        findings.append("Requirements exist but no changed code was detected in git diff.")
    if changed_without_tests:
        findings.append("Changed behavior appears untested (no requirement-linked tests).")
    if tests_not_mapped:
        findings.append("Some tests are not mapped to requirements.")
    if not findings:
        findings.append("No obvious requirement/test drift detected.")
    human_review = [
        "Review changed files and confirm corresponding requirement IDs are updated.",
        "Confirm each changed requirement has at least one mapped test case.",
        "Confirm work-item intent aligns with implementation and verification results.",
    ]
    return {
        "changed_files": changed,
        "changed_code_files": changed_code,
        "requirement_ids": sorted(req_ids),
        "mapped_test_requirement_ids": sorted(mapped_test_req_ids),
        "work_item_intents": work_item_intents,
        "flags": {
            "changed_code_without_requirement": changed_without_req,
            "requirement_without_changed_code": req_without_changes,
            "changed_behavior_without_test": changed_without_tests,
            "tests_not_mapped_to_requirement": bool(tests_not_mapped),
        },
        "tests_not_mapped": tests_not_mapped,
        "findings": findings,
        "human_review_workflow": human_review,
    }


@click.command(name="quickstart")
@click.option("--project-type", type=click.Choice(PROJECT_TYPES), default=None)
@click.option("--mode", type=click.Choice(MODES), default=None)
@click.option("--no-interactive", is_flag=True, default=False)
@click.option("--project-dir", type=click.Path(exists=True), default=".")
@click.pass_context
def quickstart_cmd(
    ctx: click.Context,
    project_type: str | None,
    mode: str | None,
    no_interactive: bool,
    project_dir: str,
) -> None:
    root = Path(project_dir).resolve()
    chosen_project_type = project_type
    chosen_mode = mode
    chosen_integrations: list[str] = ["none"]
    chosen_ci = "github-actions"
    chosen_esdb = "yes"

    if not no_interactive:
        if not chosen_project_type:
            chosen_project_type = click.prompt(
                "Project type",
                type=click.Choice(PROJECT_TYPES),
                default="python-cli",
            )
        if not chosen_mode:
            chosen_mode = click.prompt("Governance mode", type=click.Choice(MODES), default="lite")
        raw_integrations = click.prompt(
            "Agent integrations (comma separated)",
            default="claude-code,cursor",
        )
        parsed = _parse_multi(raw_integrations, AGENT_CHOICES)
        chosen_integrations = parsed or ["none"]
        chosen_ci = click.prompt(
            "CI preference",
            type=click.Choice(CI_CHOICES),
            default="github-actions",
        )
        chosen_esdb = click.prompt("Enable ESDB", type=click.Choice(("yes", "no")), default="yes")
    else:
        chosen_project_type = chosen_project_type or "python-cli"
        chosen_mode = chosen_mode or "lite"
        chosen_integrations = ["none"]

    created = _ensure_governance_mode_files(root, chosen_mode)
    state_dir = root / ".specsmith"
    state_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "project_type": chosen_project_type,
        "mode": chosen_mode,
        "integrations": chosen_integrations,
        "ci": chosen_ci,
        "esdb": chosen_esdb,
        "generated_files": created,
    }
    (state_dir / "quickstart.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (state_dir / "governance-mode").write_text(chosen_mode, encoding="utf-8")

    from specsmith.sync import run_sync

    run_sync(root)
    click.echo(
        f"quickstart complete: mode={chosen_mode}, project_type={chosen_project_type}, "
        f"files={len(created)}"
    )

    main_cmd = ctx.find_root().command
    doctor_cmd = main_cmd.commands.get("doctor") if isinstance(main_cmd, click.Group) else None  # noqa: E501
    if doctor_cmd is not None and doctor_cmd.callback is not None:
        click.echo("Running doctor automatically...")
        doctor_cmd.callback(project_dir=str(root), onboarding=False, as_json=False)


@click.command(name="expand")
@click.option("--to", "target_mode", type=click.Choice(("team", "regulated")), required=True)
@click.option("--project-dir", type=click.Path(exists=True), default=".")
def expand_cmd(target_mode: str, project_dir: str) -> None:
    root = Path(project_dir).resolve()
    created = _ensure_governance_mode_files(root, target_mode)
    state_dir = root / ".specsmith"
    state_dir.mkdir(parents=True, exist_ok=True)
    (state_dir / "governance-mode").write_text(target_mode, encoding="utf-8")
    click.echo(f"expanded governance to {target_mode}; created {len(created)} file(s)")


@click.command(name="verify-integrations")
@click.option("--project-dir", type=click.Path(exists=True), default=".")
@click.option("--json", "as_json", is_flag=True, default=False)
def verify_integrations_cmd(project_dir: str, as_json: bool) -> None:
    root = Path(project_dir).resolve()
    checks: list[dict[str, Any]] = []
    targets = {
        "claude-code": root / "CLAUDE.md",
        "cursor": root / ".cursor" / "rules" / "governance.mdc",
        "agent-skill": root / ".agents" / "skills" / "SKILL.md",
        "copilot": root / ".github" / "copilot-instructions.md",
    }
    for name, path in targets.items():
        exists = path.is_file()
        checks.append({"integration": name, "path": str(path), "exists": exists})

    mcp_path = root / ".specsmith" / "mcp.json"
    mcp_ok = False
    mcp_error = ""
    if mcp_path.is_file():
        try:
            mcp_payload = json.loads(mcp_path.read_text(encoding="utf-8"))
            servers = mcp_payload.get("servers") if isinstance(mcp_payload, dict) else None
            mcp_ok = isinstance(servers, list) and all(
                isinstance(server, dict) and server.get("id") and server.get("command")
                for server in servers
            )
        except ValueError as exc:
            mcp_error = str(exc)
    else:
        mcp_error = "missing"
    checks.append(
        {
            "integration": "mcp-config",
            "path": str(mcp_path),
            "exists": mcp_ok,
            "error": mcp_error,
        }
    )

    failing = [row for row in checks if not row["exists"]]
    payload = {"checks": checks, "passed": len(failing) == 0}
    if as_json:
        click.echo(json.dumps(payload, indent=2))
    else:
        for row in checks:
            icon = "✓" if row["exists"] else "✗"
            click.echo(f"{icon} {row['integration']}: {row['path']}")
            if row.get("error"):
                click.echo(f"  {row['error']}")
    if failing:
        raise SystemExit(1)


def _build_import_group(
    legacy_cmd: click.Command | None,
) -> click.Group:
    @click.group(name="import", invoke_without_command=True)
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--force", is_flag=True, default=False)
    @click.option("--guided", is_flag=True, default=False)
    @click.option("--dry-run", is_flag=True, default=False)
    @click.option("--yes", "-y", "auto_yes", is_flag=True, default=False)
    @click.pass_context
    def import_group(
        ctx: click.Context,
        project_dir: str,
        force: bool,
        guided: bool,
        dry_run: bool,
        auto_yes: bool,
    ) -> None:
        if ctx.invoked_subcommand is not None:
            return
        if legacy_cmd is None:
            click.echo("No legacy import command found.")
            raise SystemExit(1)
        callback = legacy_cmd.callback
        if callback is None:
            click.echo("Legacy import callback unavailable.")
            raise SystemExit(1)
        callback(
            project_dir=project_dir,
            force=force,
            guided=guided,
            dry_run=dry_run,
            auto_yes=auto_yes,
        )

    @import_group.command(name="spec-kit")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--dry-run", is_flag=True, default=False)
    def import_spec_kit(project_dir: str, dry_run: bool) -> None:
        report = _import_from_kind(Path(project_dir).resolve(), "spec-kit", dry_run)
        click.echo(json.dumps(report, indent=2))

    @import_group.command(name="openspec")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--dry-run", is_flag=True, default=False)
    def import_openspec(project_dir: str, dry_run: bool) -> None:
        report = _import_from_kind(Path(project_dir).resolve(), "openspec", dry_run)
        click.echo(json.dumps(report, indent=2))

    @import_group.command(name="bmad")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--dry-run", is_flag=True, default=False)
    def import_bmad(project_dir: str, dry_run: bool) -> None:
        report = _import_from_kind(Path(project_dir).resolve(), "bmad", dry_run)
        click.echo(json.dumps(report, indent=2))

    return import_group


def _build_export_group(
    legacy_cmd: click.Command | None,
) -> click.Group:
    @click.group(name="export", invoke_without_command=True)
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--output", type=click.Path(), default=None)
    @click.pass_context
    def export_group(ctx: click.Context, project_dir: str, output: str | None) -> None:
        if ctx.invoked_subcommand is not None:
            return
        if legacy_cmd is None:
            click.echo("No legacy export command found.")
            raise SystemExit(1)
        callback = legacy_cmd.callback
        if callback is None:
            click.echo("Legacy export callback unavailable.")
            raise SystemExit(1)
        callback(project_dir=project_dir, output=output)

    @export_group.command(name="markdown")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--out", "out_path", type=click.Path(), default="export.md")
    def export_markdown(project_dir: str, out_path: str) -> None:
        root = Path(project_dir).resolve()
        payload = _export_payload(root)
        md = _to_markdown_export(payload)
        Path(out_path).write_text(md, encoding="utf-8")
        click.echo(f"wrote markdown export: {out_path}")

    @export_group.command(name="json")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--out", "out_path", type=click.Path(), default="export.json")
    def export_json(project_dir: str, out_path: str) -> None:
        root = Path(project_dir).resolve()
        payload = _export_payload(root)
        Path(out_path).write_text(json.dumps(payload, indent=2), encoding="utf-8")
        click.echo(f"wrote json export: {out_path}")

    @export_group.command(name="github-issues")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--out", "out_path", type=click.Path(), default="issues.md")
    def export_github_issues(project_dir: str, out_path: str) -> None:
        root = Path(project_dir).resolve()
        payload = _export_payload(root)
        audit_rows = payload["audit"]["results"]
        lines = ["# Proposed GitHub Issues", ""]
        for row in audit_rows:
            if row["passed"]:
                continue
            lines.append(f"- [ ] {row['name']}: {row['message']}")
        if len(lines) == 2:
            lines.append("- [ ] Governance maintenance: no failing audit findings at export time.")
        lines.append("")
        Path(out_path).write_text("\n".join(lines), encoding="utf-8")
        click.echo(f"wrote github issues plan: {out_path}")

    @export_group.command(name="evidence-pack")
    @click.option("--project-dir", type=click.Path(exists=True), default=".")
    @click.option("--out", "out_path", type=click.Path(), default="evidence-pack.zip")
    def export_evidence_pack(project_dir: str, out_path: str) -> None:
        root = Path(project_dir).resolve()
        files = [
            root / "AGENTS.md",
            root / "LEDGER.md",
            root / "docs" / "REQUIREMENTS.md",
            root / "docs" / "TESTS.md",
            root / ".specsmith" / "requirements.json",
            root / ".specsmith" / "testcases.json",
        ]
        with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for file_path in files:
                if file_path.is_file():
                    archive.write(file_path, arcname=str(file_path.relative_to(root)))
        click.echo(f"wrote evidence pack: {out_path}")

    return export_group


@click.group(name="github")
def github_group() -> None:
    """GitHub issue planning and creation helpers."""


@github_group.command(name="issue-plan")
@click.option("--from", "source", type=click.Choice(("audit",)), default="audit")
@click.option("--output", "output_path", type=click.Path(), default="issues.md")
@click.option("--project-dir", type=click.Path(exists=True), default=".")
def github_issue_plan_cmd(source: str, output_path: str, project_dir: str) -> None:
    from specsmith.auditor import run_audit

    root = Path(project_dir).resolve()
    report = run_audit(root)
    lines = [
        "# Proposed issues from audit",
        "",
        f"Source: {source}",
        "",
    ]
    for row in report.results:
        if row.passed:
            continue
        lines.append(f"- [ ] {row.name}: {row.message}")
    if len(lines) <= 4:
        lines.append("- [ ] Governance housekeeping: no failing findings at plan generation time.")
    lines.append("")
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    click.echo(f"issue plan written: {output_path}")


@github_group.command(name="issue-create")
@click.option("--from", "source_path", type=click.Path(exists=True), required=True)
@click.option("--dry-run", is_flag=True, default=False)
@click.option("--repo", default="layer1labs/specsmith")
def github_issue_create_cmd(source_path: str, dry_run: bool, repo: str) -> None:
    titles = _parse_issue_plan(Path(source_path))
    # Skip the gh network call in dry-run mode — dedup is only needed when actually creating
    open_titles = set() if dry_run else _gh_open_issue_titles(repo)
    created = 0
    skipped = 0
    for title in titles:
        lowered = title.strip().lower()
        if lowered in open_titles:
            skipped += 1
            click.echo(f"skip duplicate title: {title}")
            continue
        if dry_run:
            created += 1
            click.echo(f"dry-run create: {title}")
            continue
        body = "Generated by specsmith github issue-create."
        cmd = [
            "gh",
            "issue",
            "create",
            "-R",
            repo,
            "--title",
            title,
            "--body",
            body,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=False)
        if result.returncode == 0:
            created += 1
        else:
            click.echo(f"failed to create issue: {title} ({result.stderr.strip()})")
    click.echo(f"issue-create complete: created={created}, skipped={skipped}, dry_run={dry_run}")


@click.command(name="drift-check")
@click.option("--project-dir", type=click.Path(exists=True), default=".")
@click.option("--json", "as_json", is_flag=True, default=False)
def drift_check_cmd(project_dir: str, as_json: bool) -> None:
    payload = _drift_report(Path(project_dir).resolve())
    if as_json:
        click.echo(json.dumps(payload, indent=2))
        return
    click.echo("drift check")
    for finding in payload["findings"]:
        click.echo(f"- {finding}")
    click.echo("")
    click.echo("Human review workflow:")
    for step in payload["human_review_workflow"]:
        click.echo(f"- {step}")


@click.command(name="trace-score")
@click.option("--project-dir", type=click.Path(exists=True), default=".")
@click.option("--json", "as_json", is_flag=True, default=False)
@click.option("--ci", "ci_mode", is_flag=True, default=False)
@click.option("--threshold", type=float, default=80.0)
def trace_score_cmd(project_dir: str, as_json: bool, ci_mode: bool, threshold: float) -> None:
    payload = _calculate_trace_score(Path(project_dir).resolve())
    if as_json:
        click.echo(json.dumps(payload, indent=2))
    else:
        click.echo(f"trace score: {payload['score']:.2f}/100")
        click.echo("breakdown:")
        for key, value in payload["metrics"].items():
            click.echo(f"- {key}: {value:.2f}")
        click.echo("recommendations:")
        for row in payload["recommendations"]:
            click.echo(f"- {row}")
    if ci_mode and payload["score"] < threshold:
        raise SystemExit(1)


def register_reporting_commands(main: click.Group) -> None:
    main.add_command(quickstart_cmd)
    main.add_command(expand_cmd)
    main.add_command(github_group)
    main.add_command(verify_integrations_cmd)
    main.add_command(drift_check_cmd)

    legacy_import = main.commands.get("import")
    main.commands["import"] = _build_import_group(legacy_import)

    legacy_export = main.commands.get("export")
    main.commands["export"] = _build_export_group(legacy_export)

    trace_group = main.commands.get("trace")
    if isinstance(trace_group, click.Group):
        trace_group.add_command(trace_score_cmd, name="score")
